- hosts: minikube
  become: true
  tasks:
     - name: create new deployment
       command: "kubectl apply -f /home/ubuntu/Deployment.yml"
       environment:
         KUBECONFIG: "/home/ubuntu/.kube/config"  # Explicit path
     - name: create new service
       command: "kubectl apply -f /home/ubuntu/Service.yml"
       environment:
         KUBECONFIG: "/home/ubuntu/.kube/config"  # Explicit path
